# 头部菜单，title: link
menu:
  # 自传: /about
  # 友情链接: /links
  分类: /categories
  归档: /archives


# 是否显示目录
TOC: false

# 是否自动播放音乐
autoplay: false

# 是否显示网易云音乐外链
mp3: true

# 首页封面图, 为空时取文章的cover作为封面
welcome_cover:  /img/welcome-cover2.jpg

# 默认文章封面图
cover: /img/cover2.jpg

# 是否关闭默认滚动条
scrollbar: true

# Gitalk 评论插件（https://github.com/gitalk/gitalk）
gitalk:
    # 是否自动展开评论框
    autoExpand: false
    # 应用编号
    clientID: '2555f71bc5b74cea87dc'
    # 应用秘钥
    clientSecret: '8b76f3e02472ccde8aaf6bea67a45b4001ccdbb8'
    # issue仓库名
    repo: 'HexoContext'
    # Github名
    owner: 'ljh19951221'
    # Github名
    admin: ['ljh19951221']
    # Ensure uniqueness and length less than 50
    id: location.pathname
    # Facebook-like distraction free mode
    distractionFreeMode: false

# 网站关键字
keywords: Fechin

# 要使用google_analytics进行统计的话，这里需要配置ID
google_analytics: 

# 网站ico
favicon: /img/favicon.png

# rss文件
rss: atom.xml
